name: Auto Comment on Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment to Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
      - name: Add Comment to Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;

            const commentBody1 = `
Hello there! 👋 Thanks for opening this issue and contributing to our **IoT-AI-Public-Safety** project.

**Here's what you need to know:**

1.  **Issue Review:** Our maintainers will look at this soon and assign it to someone. Please be patient!
2.  **Next Steps:** You can help us speed things up by making sure your issue is complete and follows our **[Contributing Guidelines](CONTRIBUTING.md)**.
3.  **Show Support:** If you like our project, remember to give the repository a ⭐!

We appreciate your help!
`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody1
            });

